NVTBaiDanhGiaGiuaKy/Models/NvtProduct.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NVTBaiDanhGiaGiuaKy.Models
{
    public class NvtProduct
    {
        public int NvtId { get; set; }

        [DisplayName("NVT: Họ và tên")]
        [Required(ErrorMessage = "NVT: chưa nhập dữ liệu")]
        [StringLength(100, MinimumLength = 5, ErrorMessage = "NVT: Họ tên chứa tối thiểu 5 ký tự và tối đa 100")]
        [RegularExpression(@"[A-Za-z]+", ErrorMessage = "NVT: Họ tên chỉ chứa các kí tự hoặc khoảng trắng")]
        public string NvtFullName { get; set; }

        [DisplayName("NVT: Ảnh")]
        [Required(ErrorMessage = "NVT: chưa nhập dữ liệu")]
        public string NvtImage { get; set; }

        [DisplayName("NVT: Số Lượng")]
        [Required(ErrorMessage = "NVT: chưa nhập dữ liệu")]
        [Range(1, 100, ErrorMessage = "NVT: Số lượng từ 1 đén 100")]
        public int NvtQuantity { get; set; }

        [DisplayName("NVT: Giá")]
        [Required(ErrorMessage = "NVT: chưa nhập dữ liệu")]
        [Range(0.01, double.MaxValue, ErrorMessage = "NVT:Giá phải lớn hơn 0")]
        public decimal NvtPrice { get; set; }


        [Required(ErrorMessage = "NVT: chưa nhập dữ liệu")]
        public bool NvtisActive { get; set; }

    }
}

NVTBaiDanhGiaGiuaKy/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NVTBaiDanhGiaGiuaKy.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

NVTBaiDanhGiaGiuaKy/Controllers/NVTProductController.cs
using NVTBaiDanhGiaGiuaKy.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NVTBaiDanhGiaGiuaKy.Controllers
{
    public class NVTProductController : Controller
    {
        private static List<NvtProduct> nvtProducts = new List<NvtProduct>()
        {
            new NvtProduct(){NvtId=221090012,NvtFullName="Nguyễn Văn Thạo",NvtImage="https://example.com/laptop.jpg",NvtQuantity=10,NvtPrice=1500,NvtisActive=true},
            new NvtProduct(){NvtId=221090011,NvtFullName="Nguyễn Thạo Văn",NvtImage="https://example.com/laptop.jpg",NvtQuantity=10,NvtPrice=1500,NvtisActive=true},
        };
        // GET: NVT
        public ActionResult NvtIndex()
        {
            return View(nvtProducts);
        }

        public ActionResult NvtCreate()
        {
            var nvtModel = new NvtProduct();
            return View(nvtModel);
        }

        [HttpPost]
         public ActionResult NvtCreate(NvtProduct newNvtProduct)
        {
            if (!ModelState.IsValid)
            {
                return View(newNvtProduct);
            }

            // Tạo ID mới cho sản phẩm
            if (nvtProducts.Any())
            {
                newNvtProduct.NvtId = nvtProducts.Max(p => p.NvtId) + 1;
            }
            else
            {
                newNvtProduct.NvtId = 1; // Nếu danh sách rỗng, bắt đầu với ID = 1
            }

            nvtProducts.Add(newNvtProduct);
            return RedirectToAction("NvtIndex");
        }
        public ActionResult NvtEdit(int id)
        {
            var product = nvtProducts.Find(p => p.NvtId == id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);

        }
        public ActionResult NvtDetails(int id)
        {
            var product = nvtProducts.Find(p => p.LvhId == id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LvhEdit(NvtProduct lvhProduct)
        {
            if (!ModelState.IsValid)
            {
                return View(lvhProduct);
            }

            var product = NvtProducts.Find(p => p.LvhId == lvhProduct.LvhId);
            if (product == null)
            {
                return HttpNotFound();
            }

            // Cập nhật các giá trị
            product.LvhFullName = lvhProduct.NvtFullName;
            product.LvhImage = lvhProduct.NvtImage;
            product.LvhQuantity = lvhProduct.NvtQuantity;
            product.LvhPrice = lvhProduct.NvtPrice;
            product.LvhIsActive = lvhProduct.NvtisActive;

            return RedirectToAction("LvhIndex");
        }
    }
}

NVTBaiDanhGiaGiuaKy/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

NVTBaiDanhGiaGiuaKy/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

NVTBaiDanhGiaGiuaKy/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

NVTBaiDanhGiaGiuaKy/Views/NVTProduct/NvtCreate.cshtml
@model NVTBaiDanhGiaGiuaKy.Models.NvtProduct

@{
    ViewBag.Title = "NvtCreate";
}

<h2>NvtCreate: Nguyễn Văn Thạo</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NvtProduct</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NvtId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NvtId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NvtId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NvtFullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NvtFullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NvtFullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NvtImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NvtImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NvtImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NvtQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NvtQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NvtQuantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NvtPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NvtPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NvtPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NvtisActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.NvtisActive)
                    @Html.ValidationMessageFor(model => model.NvtisActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                <a href="@Url.Action("NvtIndex", "NVTProduct")" name="nvtBtnBack" class="btn btn-success">Nvt: Back</a>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NVTBaiDanhGiaGiuaKy/Views/NVTProduct/NvtEdit.cshtml
@model NVTBaiDanhGiaGiuaKy.Models.NvtProduct

@{
    ViewBag.Title = "NvtEdit";
}

<h2>NvtEdit: Nguyễn Văn Thạo</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NvtProduct</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NvtId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NvtId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NvtId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NvtFullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NvtFullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NvtFullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NvtImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NvtImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NvtImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NvtQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NvtQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NvtQuantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NvtPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NvtPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NvtPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NvtisActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.NvtisActive)
                    @Html.ValidationMessageFor(model => model.NvtisActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
                <a href="@Url.Action("NvtIndex", "NVTProduct")" name="nvtBtnBack" class="btn btn-success">Nvt: Back</a>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NVTBaiDanhGiaGiuaKy/Views/NVTProduct/NvtIndex.cshtml
@model IEnumerable<NVTBaiDanhGiaGiuaKy.Models.NvtProduct>

@{
    ViewBag.Title = "NvtIndex";
}

<h2>NvtIndex</h2>

<p>
    @Html.ActionLink("Create New", "NVTCreate")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NvtId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NvtFullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NvtImage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NvtQuantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NvtPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NvtisActive)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NvtId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NvtFullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NvtImage)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NvtQuantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NvtPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NvtisActive)
        </td>
        <td>
            @Html.ActionLink("NVT:Edit", "NVTEdit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("NVT:Details", "NVTDetails", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("NVT:Delete", "NVTDelete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

NVTBaiDanhGiaGiuaKy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nguyễn Văn Thạo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("NVT: hiển thị list product", "NvtIndex", "NVTProduct")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>